import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';
import { Activity, Dumbbell, History, LineChart as LineChartIcon, Wind, Flame, Smile, PersonStanding, Clock, Stethoscope, Camera, PieChart, TrendingUp, AlertTriangle, Ambulance, MapPin, Heart, Search, Sun, CloudRain, Plus, Download, FileText, User, ShieldCheck } from 'lucide-react';
import { useNavigate, Link } from 'react-router-dom';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import {
  Chart as ChartJS, CategoryScale, LinearScale, PointElement,
  LineElement, BarElement, Title, Tooltip, Legend, Filler
} from 'chart.js';
import { Line, Bar } from 'react-chartjs-2';

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, BarElement, Title, Tooltip, Legend, Filler);

const Dashboard = () => {
    const { user, API_URL } = useAuth();
    const navigate = useNavigate();
    const [exercises, setExercises] = useState([]);
    const [history, setHistory] = useState([]);
    const [currentTime, setCurrentTime] = useState(new Date().toLocaleTimeString());
    const [showLogModal, setShowLogModal] = useState(false);
    const [manualVitals, setManualVitals] = useState({ bpm: 72, spo2: 98, bp: "120/80", temp: 98.6 });
    const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);

    const generatePassport = async () => {
        setIsGeneratingPDF(true);
        const doc = new jsPDF();
        const date = new Date().toLocaleDateString();

        // Title
        doc.setFontSize(22);
        doc.setTextColor(14, 165, 233); // Neon Blue
        doc.text('NEXAHEALTH AI: CLINICAL PASSPORT', 105, 20, { align: 'center' });

        doc.setFontSize(10);
        doc.setTextColor(100, 116, 139);
        doc.text(`Generated on: ${date}`, 105, 28, { align: 'center' });

        // Patient Header
        doc.setFillColor(241, 245, 249);
        doc.rect(15, 35, 180, 25, 'F');
        doc.setFontSize(12);
        doc.setTextColor(30, 41, 59);
        doc.text('PATIENT IDENTIFICATION', 20, 42);
        doc.setFontSize(10);
        doc.text(`NAME: ${user?.name || 'MANLEEN SINGH'}`, 20, 50);
        doc.text('BLOOD TYPE: B POSITIVE', 100, 50);
        doc.text('DOB: 12/04/1998', 20, 55);
        doc.text('ID: NX-8829-LH', 100, 55);

        // Core Vitals
        doc.setFontSize(14);
        doc.setTextColor(14, 165, 233);
        doc.text('LATEST VITAL TELEMETRY', 20, 75);
        doc.setLineWidth(0.5);
        doc.setDrawColor(14, 165, 233);
        doc.line(20, 78, 190, 78);

        const vitals = [
            ['Metric', 'Current Value', 'Clinical Status'],
            ['Heart Rate', `${manualVitals.bpm} BPM`, 'STABLE'],
            ['Oxygen Saturation (SpO2)', `${manualVitals.spo2}%`, 'OPTIMAL'],
            ['Blood Pressure', `${manualVitals.bp}`, 'NORMAL'],
            ['Body Temp', `${manualVitals.temp}°F`, 'NORMAL'],
        ];

        let yPos = 85;
        doc.setFontSize(10);
        doc.setTextColor(51, 65, 85);
        vitals.forEach((row, i) => {
            if (i === 0) doc.setFont(undefined, 'bold');
            else doc.setFont(undefined, 'normal');
            doc.text(row[0], 20, yPos);
            doc.text(row[1], 80, yPos);
            doc.text(row[2], 140, yPos);
            yPos += 8;
        });

        // AI Diagnosis Summary
        doc.setFontSize(14);
        doc.setTextColor(14, 165, 233);
        doc.text('AI DIAGNOSTIC HEALTH SUMMARY', 20, 140);
        doc.line(20, 143, 190, 143);

        doc.setFontSize(10);
        doc.setTextColor(51, 65, 85);
        doc.text('Summary Statement:', 20, 150);
        doc.setFont(undefined, 'normal');
        
        const latestSymptom = history.find(h => h.type === 'symptom');
        const latestFace = history.find(h => h.type === 'face_scan');
        
        let summaryText = `Patient exhibits stable vitals. `;
        if(latestFace) summaryText += `Clinical face scan (${latestFace.data.skinCondition}) detected with ${latestFace.data.confidence}% confidence. `;
        if(latestSymptom) summaryText += `Recent symptom log indicates: "${latestSymptom.data.symptoms}". `;
        summaryText += "Recommend continuing daily telemetry monitoring and standard exercise programs.";

        const splitText = doc.splitTextToSize(summaryText, 170);
        doc.text(splitText, 20, 157);

        // Security / Footer
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text('This document is a clinical summary generated by NexaHealth Clinical AI.', 105, 280, { align: 'center' });
        doc.text('VERIFIED ENCRYPTION ID: NX-PASS-7729-AX82', 105, 285, { align: 'center' });

        doc.save(`NexaHealth_Passport_${user?.name || 'User'}.pdf`);
        setIsGeneratingPDF(false);
    };

    useEffect(() => {
        const timer = setInterval(() => {
            setCurrentTime(new Date().toLocaleTimeString());
        }, 1000);
        return () => clearInterval(timer);
    }, []);

    useEffect(() => {
        fetchExercises();
        fetchHistory();
    }, []);

    const fetchExercises = async () => {
        try {
            const res = await axios.get(`${API_URL}/ai/exercises`);
            setExercises(res.data);
        } catch (e) { console.error('Error fetching exercises', e); }
    };

    const fetchHistory = async () => {
        try {
            const res = await axios.get(`${API_URL}/health/history`);
            setHistory(res.data);
        } catch (e) { console.error('Error fetching history', e); }
    };

    const renderIcon = (type) => {
        switch(type) {
            case 'walk': return <PersonStanding color="var(--accent-neon-blue)" size={24} />;
            case 'yoga': return <Activity color="var(--accent-neon-purple)" size={24} />;
            case 'dumbbell': return <Dumbbell color="var(--accent-neon-teal)" size={24} />;
            case 'wind': return <Wind color="#c4b5fd" size={24} />;
            case 'flame': return <Flame color="#fb923c" size={24} />;
            case 'smile': return <Smile color="#a78bfa" size={24} />;
            default: return <Activity color="var(--text-secondary)" size={24} />;
        }
    };

    // Calculate Weekly Progress
    const oneWeekAgo = new Date();
    oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);
    const recentHistory = history.filter(h => new Date(h.createdAt) >= oneWeekAgo);
    const recentSymptoms = recentHistory.filter(h => h.type === 'symptom').length;
    const recentFaceScans = recentHistory.filter(h => h.type === 'face_scan').length;

    // Process data for charts
    const processChartData = () => {
        const sortedHistory = [...history].sort((a,b) => new Date(a.createdAt) - new Date(b.createdAt));
        const symptomData = {};
        const faceData = {};
        
        sortedHistory.forEach(log => {
            if (!log || !log.createdAt) return;
            const dateStr = new Date(log.createdAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
            if (log.type === 'symptom' && log.data) {
                symptomData[dateStr] = (symptomData[dateStr] || 0) + 1;
            } else if (log.type === 'face_scan' && log.data) {
                if(!faceData[dateStr]) faceData[dateStr] = [];
                faceData[dateStr].push(log.data.confidence || 0);
            }
        });

        const allDates = [...new Set([...Object.keys(symptomData), ...Object.keys(faceData)])].slice(-7);

        return {
            dates: allDates.length ? allDates : ['No Data'],
            symptoms: allDates.length ? allDates.map(d => symptomData[d] || 0) : [0],
            faceConfidences: allDates.length ? allDates.map(d => {
                if(!faceData[d]) return 0;
                return faceData[d].reduce((a,b)=>a+b,0) / faceData[d].length;
            }) : [0]
        };
    };

    const chartDataObj = processChartData();

    const symptomChartData = {
        labels: chartDataObj.dates,
        datasets: [{
            label: 'Symptoms Tracked',
            data: chartDataObj.symptoms,
            borderColor: 'rgba(167, 139, 250, 1)',
            backgroundColor: 'rgba(167, 139, 250, 0.2)',
            tension: 0.4,
            fill: true
        }]
    };

    const faceChartData = {
        labels: chartDataObj.dates,
        datasets: [{
            label: 'Avg Scan Confidence (%)',
            data: chartDataObj.faceConfidences,
            backgroundColor: 'rgba(14, 165, 233, 0.6)',
            borderRadius: 4
        }]
    };

    const chartOptions = {
        responsive: true,
        plugins: { legend: { labels: { color: '#e2e8f0' } } },
        scales: {
            x: { ticks: { color: '#94a3b8' }, grid: { color: 'rgba(255,255,255,0.05)' } },
            y: { ticks: { color: '#94a3b8' }, grid: { color: 'rgba(255,255,255,0.05)', beginAtZero: true } }
        }
    };

    return (
        <div style={{ paddingBottom: '40px' }}>
            {/* Header & Weekly Report */}
            <div style={{ marginBottom: '30px', display: 'flex', flexWrap: 'wrap', gap: '24px', justifyContent: 'space-between', alignItems: 'center' }}>
                <div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px' }}>
                        <h1 className="heading-gradient" style={{ fontSize: '2.5rem', margin: 0 }}>Welcome, {user?.name}</h1>
                        <span style={{ background: 'rgba(255,255,255,0.05)', padding: '4px 12px', borderRadius: '8px', fontSize: '0.9rem', color: 'var(--accent-neon-blue)', border: '1px solid rgba(14, 165, 233, 0.2)', fontWeight: 'bold', minWidth: '100px', textAlign: 'center' }}>
                            {currentTime}
                        </span>
                    </div>
                    <p style={{ color: 'var(--text-secondary)', fontSize: '1.1rem' }}>Clinical status: <span style={{color: 'var(--accent-neon-teal)', fontWeight: 'bold'}}>STABLE</span> • System Uptime: 99.9%</p>
                </div>
                
                <button 
                  className="btn-outline" 
                  style={{ display: 'flex', alignItems: 'center', gap: '10px', padding: '12px 24px', fontWeight: 'bold' }} 
                  onClick={generatePassport}
                  disabled={isGeneratingPDF}
                >
                    <Download size={20} color="var(--accent-neon-blue)" /> 
                    {isGeneratingPDF ? 'PROCESSING...' : 'HEALTH PASSPORT'}
                </button>
                
                <div className="glass-panel" style={{ display: 'flex', gap: '24px', flexWrap: 'wrap', alignItems: 'center', padding: '16px 24px', border: '1px solid rgba(20, 184, 166, 0.3)' }}>
                    <div>
                        <div style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', marginBottom: '4px', display: 'flex', alignItems: 'center', gap: '6px' }}><TrendingUp size={16} color="var(--accent-neon-teal)"/> Weekly Progress</div>
                        <div style={{ fontSize: '1.8rem', fontWeight: 'bold', color: 'var(--text-primary)' }}>{recentHistory.length} <span style={{fontSize:'1rem', color:'var(--text-secondary)', fontWeight:'normal'}}>Logs</span></div>
                    </div>
                    <div style={{ height: '40px', width: '1px', background: 'rgba(255,255,255,0.1)' }}></div>
                    <div>
                        <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>Symptoms Logged</div>
                        <div style={{ fontSize: '1.2rem', fontWeight: 'bold', color: 'var(--accent-neon-purple)' }}>{recentSymptoms}</div>
                    </div>
                    <div>
                        <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>Face Scans</div>
                        <div style={{ fontSize: '1.2rem', fontWeight: 'bold', color: 'var(--accent-neon-blue)' }}>{recentFaceScans}</div>
                    </div>
                </div>
            </div>
            
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(350px, 1fr))', gap: '24px', marginBottom: '30px' }}>
                {/* Emergency Hub */}
                <div className="glass-panel" style={{ background: 'rgba(239, 68, 68, 0.05)', border: '1px solid rgba(239, 68, 68, 0.2)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '24px' }}>
                    <div style={{ display: 'flex', gap: '20px', alignItems: 'center' }}>
                        <div style={{ background: 'rgba(239, 68, 68, 0.1)', padding: '16px', borderRadius: '16px' }}>
                            <AlertTriangle color="var(--accent-red)" size={32} />
                        </div>
                        <div>
                            <h3 style={{ margin: '0 0 4px 0', color: 'var(--text-primary)' }}>Emergency Hub</h3>
                            <p style={{ margin: 0, color: 'var(--text-secondary)', fontSize: '0.9rem' }}>DMCH, Ludhiana (1.2km)</p>
                        </div>
                    </div>
                    <button onClick={() => navigate('/emergency')} className="btn-neon pulse-emergency" style={{ background: 'var(--accent-red)', padding: '12px 24px', display: 'flex', alignItems: 'center', gap: '8px', border: 'none', cursor: 'pointer', fontWeight: 'bold' }}>
                        <Ambulance size={20} /> SOS
                    </button>
                </div>

                {/* AI Telehealth */}
                <div className="glass-panel" style={{ background: 'rgba(139, 92, 246, 0.05)', border: '1px solid rgba(139, 92, 246, 0.2)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '24px' }}>
                    <div style={{ display: 'flex', gap: '20px', alignItems: 'center' }}>
                        <div style={{ background: 'rgba(139, 92, 246, 0.1)', padding: '16px', borderRadius: '16px' }}>
                            <Activity color="var(--accent-neon-purple)" size={32} />
                        </div>
                        <div>
                            <h3 style={{ margin: '0 0 4px 0', color: 'var(--text-primary)' }}>AI Telehealth</h3>
                            <p style={{ margin: 0, color: 'var(--text-secondary)', fontSize: '0.9rem' }}>Instant AI Consultation</p>
                        </div>
                    </div>
                    <Link to="/symptoms" className="btn-neon" style={{ textDecoration: 'none', padding: '12px 24px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                        <Search size={20} /> TRIAGE
                    </Link>
                </div>

                <div className="glass-panel" style={{ background: 'rgba(14, 165, 233, 0.05)', border: '1px solid rgba(14, 165, 233, 0.2)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '24px' }}>
                    <div style={{ display: 'flex', gap: '20px', alignItems: 'center' }}>
                        <div style={{ background: 'rgba(56, 189, 248, 0.1)', padding: '16px', borderRadius: '16px' }}>
                            <Sun color="var(--accent-neon-blue)" size={32} />
                        </div>
                        <div>
                            <h3 style={{ margin: '0 0 4px 0', color: 'var(--text-primary)' }}>Ludhiana: 28°C</h3>
                            <p style={{ margin: 0, color: 'var(--text-secondary)', fontSize: '0.9rem' }}>Pollen: Low • UV: High</p>
                        </div>
                    </div>
                </div>

                <div className="glass-panel" style={{ background: 'rgba(45, 212, 191, 0.05)', border: '1px solid rgba(45, 212, 191, 0.2)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '24px' }}>
                    <div style={{ display: 'flex', gap: '20px', alignItems: 'center' }}>
                        <div style={{ background: 'rgba(14, 165, 233, 0.1)', padding: '16px', borderRadius: '16px' }}>
                            <Camera color="var(--accent-neon-blue)" size={32} />
                        </div>
                        <div>
                            <h3 style={{ margin: '0 0 4px 0', color: 'var(--text-primary)' }}>Derm AI</h3>
                            <p style={{ margin: 0, color: 'var(--text-secondary)', fontSize: '0.9rem' }}>Skin Analysis Hub</p>
                        </div>
                    </div>
                    <Link to="/facescan" className="btn-neon" style={{ textDecoration: 'none', padding: '12px 24px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                        <Search size={20} /> ANALYZE
                    </Link>
                </div>
            </div>

            {/* Health Metric Hub */}
            <div className="glass-panel" style={{ padding: '24px', position: 'relative', overflow: 'hidden', marginBottom: '30px' }}>
                <div style={{ position: 'absolute', top: '-20px', right: '-20px', width: '100px', height: '100px', background: 'radial-gradient(circle, var(--accent-neon-teal) 0%, transparent 70%)', opacity: 0.1, pointerEvents: 'none' }}></div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                        <div style={{ background: 'rgba(45, 212, 191, 0.1)', padding: '10px', borderRadius: '12px' }}>
                            <Heart color="var(--accent-neon-teal)" size={24} className="pulse-emergency" style={{ animationDuration: '0.8s' }} />
                        </div>
                        <h4 style={{ margin: 0, fontSize: '1.1rem', letterSpacing: '0.5px' }}>HEALTH METRIC HUB</h4>
                    </div>
                    <span style={{ fontSize: '0.7rem', color: 'var(--accent-neon-teal)', background: 'rgba(45, 212, 191, 0.1)', padding: '4px 10px', borderRadius: '20px', border: '1px solid rgba(45, 212, 191, 0.2)' }}>LIVE TELEMETRY</span>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '20px' }} className="stats-grid">
                    <div style={{ background: 'rgba(255,255,255,0.03)', padding: '16px', borderRadius: '16px', border: '1px solid rgba(255,255,255,0.05)' }} className="hover-lift">
                        <div style={{ fontSize: '0.7rem', color: 'var(--text-secondary)', textTransform: 'uppercase', marginBottom: '8px' }}>Heart Rate</div>
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
                            <div style={{ fontSize: '1.5rem', fontWeight: 'bold', color: 'var(--text-primary)' }}>{manualVitals.bpm} <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>BPM</span></div>
                            <div style={{ width: '60px', height: '4px', background: 'rgba(239, 68, 68, 0.1)', borderRadius: '2px', overflow: 'hidden' }}>
                                <div style={{ width: `${(manualVitals.bpm/150)*100}%`, height: '100%', background: 'var(--accent-red)', boxShadow: '0 0 10px var(--accent-red)' }}></div>
                            </div>
                        </div>
                    </div>
                    <div style={{ background: 'rgba(255,255,255,0.03)', padding: '16px', borderRadius: '16px', border: '1px solid rgba(255,255,255,0.05)' }} className="hover-lift">
                        <div style={{ fontSize: '0.7rem', color: 'var(--text-secondary)', textTransform: 'uppercase', marginBottom: '8px' }}>SpO2 Level</div>
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
                            <div style={{ fontSize: '1.5rem', fontWeight: 'bold', color: 'var(--text-primary)' }}>{manualVitals.spo2} <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>%</span></div>
                            <div style={{ width: '60px', height: '4px', background: 'rgba(14, 165, 233, 0.1)', borderRadius: '2px', overflow: 'hidden' }}>
                                <div style={{ width: `${manualVitals.spo2}%`, height: '100%', background: 'var(--accent-neon-blue)', boxShadow: '0 0 10px var(--accent-neon-blue)' }}></div>
                            </div>
                        </div>
                    </div>
                    <div style={{ background: 'rgba(255,255,255,0.03)', padding: '16px', borderRadius: '16px', border: '1px solid rgba(255,255,255,0.05)' }} className="hover-lift">
                        <div style={{ fontSize: '0.7rem', color: 'var(--text-secondary)', textTransform: 'uppercase', marginBottom: '8px' }}>Blood Pressure</div>
                        <div style={{ fontSize: '1.5rem', fontWeight: 'bold', color: 'var(--text-primary)' }}>{manualVitals.bp} <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>mmHg</span></div>
                    </div>
                    <div style={{ background: 'rgba(255,255,255,0.03)', padding: '16px', borderRadius: '16px', border: '1px solid rgba(255,255,255,0.05)' }} className="hover-lift">
                        <div style={{ fontSize: '0.7rem', color: 'var(--text-secondary)', textTransform: 'uppercase', marginBottom: '8px' }}>Body Temp</div>
                        <div style={{ fontSize: '1.5rem', fontWeight: 'bold', color: 'var(--text-primary)' }}>{manualVitals.temp} <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>°F</span></div>
                    </div>
                </div>
                
                <button 
                  onClick={() => setShowLogModal(true)}
                  className="btn-outline" 
                  style={{ width: '100%', marginTop: '20px', fontSize: '0.9rem', padding: '10px' }}
                >
                  <Plus size={16} /> LOG CLINICAL DATA
                </button>

                {showLogModal && (
                    <div style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.85)', backdropFilter: 'blur(10px)', zIndex: 3000, display: 'flex', alignItems: 'center', justifyContent: 'center' }} onClick={() => setShowLogModal(false)}>
                        <div className="glass-panel" style={{ maxWidth: '400px', width: '90%', border: '1px solid var(--accent-neon-blue)' }} onClick={e => e.stopPropagation()}>
                            <h3 style={{ marginBottom: '20px', color: 'var(--accent-neon-blue)' }}>Log Vital Telemetry</h3>
                            <div style={{ display: 'grid', gap: '15px' }}>
                                <div>
                                    <label style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Heart Rate (BPM)</label>
                                    <input type="number" value={manualVitals.bpm} onChange={e => setManualVitals({...manualVitals, bpm: e.target.value})} style={{ marginBottom: 0 }} />
                                </div>
                                <div>
                                    <label style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>SpO2 (%)</label>
                                    <input type="number" value={manualVitals.spo2} onChange={e => setManualVitals({...manualVitals, spo2: e.target.value})} style={{ marginBottom: 0 }} />
                                </div>
                                <div>
                                    <label style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Blood Pressure</label>
                                    <input type="text" value={manualVitals.bp} onChange={e => setManualVitals({...manualVitals, bp: e.target.value})} style={{ marginBottom: 0 }} />
                                </div>
                                <div>
                                    <label style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Temp (°F)</label>
                                    <input type="number" step="0.1" value={manualVitals.temp} onChange={e => setManualVitals({...manualVitals, temp: e.target.value})} style={{ marginBottom: 0 }} />
                                </div>
                                <button className="btn-neon" onClick={() => setShowLogModal(false)} style={{ marginTop: '10px' }}>UPDATE HUD</button>
                            </div>
                        </div>
                    </div>
                )}
            </div>

            {/* Charts Section */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(400px, 1fr))', gap: '24px', marginBottom: '24px' }}>
                <div className="glass-panel">
                    <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '20px' }}>
                        <LineChartIcon color="var(--accent-neon-purple)" /> Symptom Tracker Trend
                    </h3>
                    <div style={{ height: '250px' }}>
                        <Line data={symptomChartData} options={chartOptions} />
                    </div>
                </div>

                <div className="glass-panel">
                    <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '20px' }}>
                        <PieChart color="var(--accent-neon-blue)" /> Face Scan Analytics
                    </h3>
                    <div style={{ height: '250px' }}>
                        <Bar data={faceChartData} options={chartOptions} />
                    </div>
                </div>
            </div>

            {/* AI Recommended Exercises */}
            <div className="glass-panel" style={{ marginBottom: '24px' }}>
                <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '20px' }}>
                    <Dumbbell color="var(--accent-neon-teal)" /> Auto-Prescribed Exercises
                </h3>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '16px' }}>
                    {exercises.length === 0 && <p style={{color: 'var(--text-secondary)'}}>Generating personal plan...</p>}
                    {exercises.map((ex, i) => (
                        <div key={i} style={{ padding: '16px', background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '12px', transition: 'transform 0.2s', display: 'flex', flexDirection: 'column' }} className="hover-lift">
                            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '12px' }}>
                                <div style={{ background: 'rgba(0,0,0,0.3)', padding: '10px', borderRadius: '12px' }}>{renderIcon(ex.iconType)}</div>
                                <h4 style={{ color: 'var(--text-primary)', margin: 0, fontSize: '1.1rem' }}>{ex.name}</h4>
                            </div>
                            <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', flexGrow: 1, marginBottom: '12px', lineHeight: '1.4' }}>{ex.description}</p>
                            
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: 'auto', borderTop: '1px solid rgba(255,255,255,0.05)', paddingTop: '12px' }}>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '6px', color: 'var(--accent-neon-blue)', fontSize: '0.85rem', fontWeight: '500' }}>
                                    <Clock size={16} /> {ex.duration}
                                </div>
                                <div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap', justifyContent: 'flex-end' }}>
                                    {ex.tags?.map(tag => (
                                        <span key={tag} style={{ background: 'rgba(20,184,166,0.15)', color: 'var(--accent-neon-teal)', padding: '4px 8px', borderRadius: '6px', fontSize: '0.7rem', fontWeight: 'bold', textTransform: 'uppercase' }}>
                                            {tag}
                                        </span>
                                    ))}
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            {/* History Section */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(400px, 1fr))', gap: '24px' }}>
                <div className="glass-panel">
                    <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '20px' }}>
                        <Stethoscope color="var(--accent-neon-purple)" /> User Symptom History
                    </h3>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', maxHeight: '350px', overflowY: 'auto', paddingRight: '8px' }} className="custom-scrollbar">
                        {history.filter(h => h.type === 'symptom').length === 0 && <p style={{color: 'var(--text-secondary)'}}>No documented symptoms.</p>}
                        {history.filter(h => h.type === 'symptom').map((log) => (
                            <div key={log._id} style={{ padding: '16px', background: 'rgba(255,255,255,0.03)', borderRadius: '8px', borderLeft: '4px solid var(--accent-neon-purple)' }}>
                                <div style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', marginBottom: '8px', display: 'flex', justifyContent: 'space-between' }}>
                                    <span>{new Date(log.createdAt).toLocaleString()}</span>
                                    <span style={{color: 'var(--accent-neon-purple)', fontWeight: 'bold'}}>Symptom</span>
                                </div>
                                <p style={{ color: 'var(--text-primary)', margin: '0 0 8px 0', fontSize: '1rem' }}>"{log.data?.symptoms || 'N/A'}"</p>
                                <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
                                    <strong>AI Diagnosis: </strong> 
                                    {Array.isArray(log.data?.causes) ? log.data.causes.slice(0, 2).join(', ') : (log.data?.causes || 'Inconclusive')}...
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                <div className="glass-panel">
                    <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '20px' }}>
                        <Camera color="var(--accent-neon-blue)" /> Face Scan History
                    </h3>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', maxHeight: '350px', overflowY: 'auto', paddingRight: '8px' }} className="custom-scrollbar">
                        {history.filter(h => h.type === 'face_scan').length === 0 && <p style={{color: 'var(--text-secondary)'}}>No face scans recorded.</p>}
                        {history.filter(h => h.type === 'face_scan').map((log) => (
                            <div key={log._id} style={{ padding: '16px', background: 'rgba(255,255,255,0.03)', borderRadius: '8px', borderLeft: '4px solid var(--accent-neon-blue)' }}>
                                <div style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', marginBottom: '8px', display: 'flex', justifyContent: 'space-between' }}>
                                    <span>{new Date(log.createdAt).toLocaleString()}</span>
                                    <span style={{color: 'var(--accent-neon-blue)', fontWeight: 'bold'}}>Face Scan</span>
                                </div>
                                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                    <div>
                                        <div style={{ color: 'var(--text-primary)', fontSize: '0.95rem' }}>Acne: <strong>{log.data?.acneDetection || 'N/A'}</strong></div>
                                        <div style={{ color: 'var(--text-secondary)', fontSize: '0.85rem', marginTop: '4px' }}>Skin: {log.data?.skinCondition || 'Analyzed'}</div>
                                    </div>
                                    <div style={{ textAlign: 'right' }}>
                                        <div style={{ fontSize: '1.2rem', fontWeight: 'bold', color: 'var(--text-primary)' }}>{log.data?.confidence || 0}%</div>
                                        <div style={{ fontSize: '0.75rem', color: 'var(--accent-neon-teal)', textTransform: 'uppercase' }}>Confidence</div>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Dashboard;
